### ISSUE TITLE
Altering subject in marshaler defaultNatsMsg

### ISSUE THREAD

**Issue by seinshah** [ThreeDotsLabs/watermill-jetstream#9]
What is the reason behind altering the publisher's subject naming during marshaling? This makes subscribing to the same subject very complicated. I had to remove this modification in my code to be able to publish and subscribe to the same topic successfully.

Changing it would be a breaking change, but there would be a way to just release the change as a feature without breaking changes. However, the reason behind having it is still unknown to me. If you agree to the change and still keep this behavior, for now, I'd be happy to create a PR.

https://github.com/ThreeDotsLabs/watermill-jetstream/blob/380cf671958b90cd331a5b2a6a727079bbfbd975/pkg/jetstream/marshaler.go#L31-L37

**Comment by ma-hartma** [comment]
Hi @seinshah,

I've already had the same problem and there's a PR #8 by @AlexCuse open to fix it!
There are some pieces in the code that rely on watermill messages having a UUID, which is optional.
I'm currently testing the new version and there may be some more modifications to fix that.

**Comment by ma-hartma** [comment]
BTW, there's also a PR open to move watermill-jetstream into watermill-nats: https://github.com/ThreeDotsLabs/watermill-nats/pull/8 and after that this repo will eventually die.

**Comment by AlexCuse** [comment]
Thanks @seinshah seems we've all run into this.  It was a carryover from the old STAN-based implementation and I don't see any reason we need it here.  I am planning to do a little house keeping today, will cut a new tag and post here when it's available if you can test.

Happy to have a PR to reintroduce this behavior as a feature but I really don't see why we need it, it's easy enough to apply this logic at call sites to Publish or introduce a wrapped publisher.

**Comment by AlexCuse** [comment]
`v0.0.6` should be good to go :crossed_fingers:

**Comment by seinshah** [comment]
Thanks @AlexCuse. I will remove the custom marshaler with this change now. It seems like a breaking change to me for those who have used the default marshaler with the previous setup though. Am I wrong, or would that be ok?

**Comment by AlexCuse** [comment]
I think its fine for a 0.x release, I don't know of a lot of people using this at the moment and two of them have ended up blocked by this issue :)  Since this will likely be deprecated for watermill-nats v2 eventually its probably what happens there that matters the most.
